version: "3"
services:

  python-3.4-test:
    build:
      args:
        - tag=3.4-alpine
      context: .
      dockerfile: testing_tools/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    network_mode: "none"
    environment:
      - isolated=true

  python-3.5-test:
    build:
      args:
        - tag=3.5-alpine
      context: .
      dockerfile: testing_tools/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    network_mode: "none"
    environment:
      - isolated=true

  python-3.7-rc-test:
      build:
        args:
          - tag=3.7-rc-alpine
        context: .
        dockerfile: testing_tools/Dockerfile
      volumes:
        - $PWD:$PWD
      working_dir: $PWD
      network_mode: "none"
      environment:
        - isolated=true

  python-3.6-test:
    build:
      args:
        - tag=3.6-alpine
      context: .
      dockerfile: testing_tools/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    network_mode: "none"
    environment:
      - isolated=true
    command: --cov=check_docker
